### ISSUE TITLE
enhancement: expansion to all maps; levels composites and story mission composites

### ISSUE THREAD

**Issue by ghramsey** [Oliver2Goetz/AIUtils#2]
Is there any chance to expand this tool for all the maps in the game?  I'd rather use it vs cheat engine since it's less prone to crashing 
the game. 

As for coordinates can you expand the function to find the coordinate offsets of each level composite and story mission composite?
 
We know not every one of them has an offset, but Matt Filer said to find the offset start at the root node and follow it through to 
 each instanced composite.   In example: We found via trial and error that the storymission composite for mission 5 has a 
X offset +16 and Z -107.  If we'd looked in the instanced composite we would not have had to do anything since it shows right there: 

![newcageeditrscreenshot](https://github.com/Oliver2Goetz/AIUtils/assets/51859157/dcfaaf62-3dca-4d7a-b543-e7cce40c0ceb)

Can we read this for other maps/levels/mission story composites and display those accordingly ?

I know this might be a bigger project than what you began with, but it's really nifty and I found it extremely useful last night 
when the current update of the command editor stripped out custom names and I had to find the coordinates to rename my stuff.

**Comment by Oliver2Goetz** [comment]
Hey @ghramsey, yes sure.
I already had it on my radar to expand it so it's great you've created an issue.
I'm planing to work on it next week but can't promise anything.

Do you know if X and Z still can be switched? If I remember correctly in mission 5 X and Z where switched or did I mix something up?

**Comment by ghramsey** [comment]
The switch of X and Z in the mission composite are based as in the screen shot I posted.  
We rounded off to 16 and -107 but we left some data on the cutting room floor.    
The coordinates though are composite dependent.   Might be 0s on some and changes on others.

That said I think the coordinates for most of the levels are OK to use as read from the Cheat Table or however you
gathered those in the current program.  It's when we use a story composite or maybe ambient environment composite 
that there would probably be an offset that's the "open cage" coordinates.

**Comment by Oliver2Goetz** [comment]
Hey @ghramsey,

I added the level offsets. The following levels do have offsets:
ENG_REACTOR_CORE (PT1), HAB_AIRPORT (M17), HAB_CORPORATEPENT, SCI_HOSPITALUPPER
These levels come with release version 0.2

As before, levels without an offset will not be listed to make the list easily clear to read. 

During checking each level I've come to something rather interesting in the reactor core and the airport level.
They both have more than one mission that plays here and only one of the missions have an offset. Eg. for the nest only the Part 1 before the nest has an offset. The mission after the nest does not have an offset. I only included these parts in the list. Keep that in mind when using.

If you are interested in the calculation and the specific offsets you can check this file `https://github.com/Oliver2Goetz/AIUtils/blob/master/AIUtils/LevelCalculation.cs`. Here's where the calculation happens with the data gathered through OpenCAGE.

Should you encounter any problems do not hesitate to contact me.
I'm way more active currently than last year and I'll try to act faster :)

**Comment by ghramsey** [comment]
COOL!   I will check this out soon.
